
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEHTHREE CLOSEHTWO CLOSELI CLOSEP CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CLOSEUL CONTENT GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENHTHREE OPENHTWO OPENLI OPENP OPENROW OPENSPAN OPENSTYLE OPENTABLE OPENULstart : portionToExtractportionToExtract : OPENHTHREE CONTENT CONTENT CLOSEHTHREE dataToExtractdataToExtract : OPENP content CLOSEPcontent : CONTENT CONTENT\n                | CONTENT CONTENT CONTENT CONTENT\n                | CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT\n                | CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT'
    
_lr_action_items = {'OPENHTHREE':([0,],[3,]),'$end':([1,2,7,11,],[0,-1,-2,-3,]),'CONTENT':([3,4,8,10,12,13,14,15,16,17,],[4,5,10,12,13,14,15,16,17,18,]),'CLOSEHTHREE':([5,],[6,]),'OPENP':([6,],[8,]),'CLOSEP':([9,12,14,16,18,],[11,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'portionToExtract':([0,],[2,]),'dataToExtract':([6,],[7,]),'content':([8,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> portionToExtract','start',1,'p_start','indiaParser.py',130),
  ('portionToExtract -> OPENHTHREE CONTENT CONTENT CLOSEHTHREE dataToExtract','portionToExtract',5,'p_portionToExtract','indiaParser.py',134),
  ('dataToExtract -> OPENP content CLOSEP','dataToExtract',3,'p_dataToExtract','indiaParser.py',141),
  ('content -> CONTENT CONTENT','content',2,'p_content','indiaParser.py',146),
  ('content -> CONTENT CONTENT CONTENT CONTENT','content',4,'p_content','indiaParser.py',147),
  ('content -> CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT','content',6,'p_content','indiaParser.py',148),
  ('content -> CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT','content',8,'p_content','indiaParser.py',149),
]
