
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CATEGORY CLOSEBOLD CLOSEDATA CLOSEDIV CLOSEH3 CLOSEH4 CLOSEHEADER CLOSEHREF CLOSENOBR CLOSEROW CLOSESCRIPT CLOSESMALL CLOSESPAN CLOSESTYLE CLOSETABLE CLOSETABLEHEADER CLOSETABLE_TABLE CONTENT GARBAGE IMAGE OPENBOLD OPENBR OPENDATA OPENDIV OPENH3 OPENH4 OPENHEADER OPENHREF OPENLINK OPENNOBR OPENROW OPENSCRIPT OPENSMALL OPENSPAN OPENSTYLE OPENTABLE OPENTABLEHEADER OPENTABLE_TABLE SPECIFICDATA SPECIFICYAXISstart : tableskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | OPENDIV skiptag\n                | CLOSEDIV skiptag\n                | OPENH3 skiptag\n                | CLOSEH3 skiptag\n               | empty dates : CONTENT CONTENT dates\n              | CONTENT SPECIFICYAXIS\n              | SPECIFICYAXIS\n    spec_data : SPECIFICDATA CONTENT\n                    | emptyscript_handle : CONTENT script_handle\n                     | OPENSCRIPT script_handle\n                     | CLOSESCRIPT script_handle\n                     | CATEGORY dates script_handle\n                     | spec_data script_handle\n                     | emptyhandlescript : OPENSCRIPT script_handle CLOSESCRIPT\n                    | emptytable : BEGINTABLE skiptag handlescriptempty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,32,],[0,-1,-24,-24,-24,-24,-24,-24,-24,-24,-24,-9,-23,-22,-2,-3,-4,-5,-6,-7,-8,-21,]),'CONTENT':([3,5,6,7,8,9,10,11,14,23,25,26,27,28,29,30,35,36,37,39,41,42,43,],[5,5,5,5,5,5,5,5,26,26,26,26,36,26,-14,39,26,41,-12,-13,36,-11,-10,]),'OPENHREF':([3,5,6,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'CLOSEHREF':([3,5,6,7,8,9,10,11,],[7,7,7,7,7,7,7,7,]),'OPENDIV':([3,5,6,7,8,9,10,11,],[8,8,8,8,8,8,8,8,]),'CLOSEDIV':([3,5,6,7,8,9,10,11,],[9,9,9,9,9,9,9,9,]),'OPENH3':([3,5,6,7,8,9,10,11,],[10,10,10,10,10,10,10,10,]),'CLOSEH3':([3,5,6,7,8,9,10,11,],[11,11,11,11,11,11,11,11,]),'OPENSCRIPT':([3,4,5,6,7,8,9,10,11,12,14,16,17,18,19,20,21,22,23,25,26,28,29,35,37,39,42,43,],[-24,14,-24,-24,-24,-24,-24,-24,-24,-9,23,-2,-3,-4,-5,-6,-7,-8,23,23,23,23,-14,23,-12,-13,-11,-10,]),'CLOSESCRIPT':([14,23,24,25,26,28,29,31,33,34,35,37,38,39,40,42,43,],[25,25,32,25,25,25,-14,-16,-17,-15,25,-12,-19,-13,-18,-11,-10,]),'CATEGORY':([14,23,25,26,28,29,35,37,39,42,43,],[27,27,27,27,27,-14,27,-12,-13,-11,-10,]),'SPECIFICDATA':([14,23,25,26,28,29,35,37,39,42,43,],[30,30,30,30,30,-14,30,-12,-13,-11,-10,]),'SPECIFICYAXIS':([27,36,41,],[37,42,37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,6,7,8,9,10,11,],[4,16,17,18,19,20,21,22,]),'empty':([3,4,5,6,7,8,9,10,11,14,23,25,26,28,35,],[12,15,12,12,12,12,12,12,12,29,29,29,29,29,29,]),'handlescript':([4,],[13,]),'script_handle':([14,23,25,26,28,35,],[24,31,33,34,38,40,]),'spec_data':([14,23,25,26,28,35,],[28,28,28,28,28,28,]),'dates':([27,41,],[35,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','extract.py',216),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','extract.py',221),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','extract.py',222),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','extract.py',223),
  ('skiptag -> OPENDIV skiptag','skiptag',2,'p_skiptag','extract.py',224),
  ('skiptag -> CLOSEDIV skiptag','skiptag',2,'p_skiptag','extract.py',225),
  ('skiptag -> OPENH3 skiptag','skiptag',2,'p_skiptag','extract.py',226),
  ('skiptag -> CLOSEH3 skiptag','skiptag',2,'p_skiptag','extract.py',227),
  ('skiptag -> empty','skiptag',1,'p_skiptag','extract.py',228),
  ('dates -> CONTENT CONTENT dates','dates',3,'p_dates','extract.py',235),
  ('dates -> CONTENT SPECIFICYAXIS','dates',2,'p_dates','extract.py',236),
  ('dates -> SPECIFICYAXIS','dates',1,'p_dates','extract.py',237),
  ('spec_data -> SPECIFICDATA CONTENT','spec_data',2,'p_spec_data','extract.py',244),
  ('spec_data -> empty','spec_data',1,'p_spec_data','extract.py',245),
  ('script_handle -> CONTENT script_handle','script_handle',2,'p_script_handle','extract.py',251),
  ('script_handle -> OPENSCRIPT script_handle','script_handle',2,'p_script_handle','extract.py',252),
  ('script_handle -> CLOSESCRIPT script_handle','script_handle',2,'p_script_handle','extract.py',253),
  ('script_handle -> CATEGORY dates script_handle','script_handle',3,'p_script_handle','extract.py',254),
  ('script_handle -> spec_data script_handle','script_handle',2,'p_script_handle','extract.py',255),
  ('script_handle -> empty','script_handle',1,'p_script_handle','extract.py',256),
  ('handlescript -> OPENSCRIPT script_handle CLOSESCRIPT','handlescript',3,'p_handlescript','extract.py',262),
  ('handlescript -> empty','handlescript',1,'p_handlescript','extract.py',263),
  ('table -> BEGINTABLE skiptag handlescript','table',3,'p_table','extract.py',267),
  ('empty -> <empty>','empty',0,'p_empty','extract.py',271),
  ('content -> CONTENT','content',1,'p_content','extract.py',276),
  ('content -> empty','content',1,'p_content','extract.py',277),
]
