
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSEDIV CLOSEHEADER CLOSEHREF CLOSELI CLOSEUL CONTENT GARBAGE OPENDIV OPENHEADER OPENHREF OPENLI OPENULstart : orderedlistorderedlist : OPENLI OPENHREF CONTENT CLOSEHREFempty :'
    
_lr_action_items = {'OPENLI':([0,],[3,]),'$end':([1,2,6,],[0,-1,-2,]),'OPENHREF':([3,],[4,]),'CONTENT':([4,],[5,]),'CLOSEHREF':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'orderedlist':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> orderedlist','start',1,'p_start','links_extract.py',54),
  ('orderedlist -> OPENLI OPENHREF CONTENT CLOSEHREF','orderedlist',4,'p_orderedlist','links_extract.py',58),
  ('empty -> <empty>','empty',0,'p_empty','links_extract.py',63),
]
