
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEH2 CLOSEH3 CLOSEHREF CLOSELI CLOSEPARA CLOSEROW CLOSESPAN CLOSETABLE CLOSEUL CONTENT GARBAGE OPENDATA OPENDIV OPENH2 OPENH3 OPENHREF OPENLI OPENPARA OPENROW OPENSPAN OPENTABLE OPENULstart : handleheader dataCell\n             | handleheader dataLI\n             | emptydataContent : CONTENT\n                   | CONTENT CONTENT\n                   | CONTENT CONTENT CONTENT\n                   | CONTENT CONTENT CONTENT CONTENT\n                   | CONTENT CONTENT CONTENT CONTENT CONTENT\n                   | CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT\n                   | CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT CONTENTreLI : dataContent dataHREF reLI\n            | dataHREF dataContent reLI\n            | dataLI : OPENLI reLI CLOSELI dataLI\n              | skiptag : OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | CONTENT skiptag\n               | emptydataSpan : OPENSPAN CLOSESPAN\n                | OPENSPAN dataContent CLOSESPAN\n                | OPENSPAN\n                | CLOSESPANdataHREF : OPENHREF dataContent CLOSEHREF\n                | OPENHREF CONTENT CONTENT CONTENT CLOSEHREF\n                | OPENHREF dataSpan CLOSEHREFdataCell : OPENPARA dataContent dataHREF dataContent dataHREF CLOSEPARA \n                | OPENPARA dataContent dataHREF CLOSEPARA\n                |handleheader : OPENH2 dataSpan dataSpan dataSpan dataSpan dataHREF dataSpan dataSpan CLOSEH2\n                    | OPENH3 OPENSPAN CONTENT CLOSESPAN dataSpan dataSpan dataHREF dataSpan dataSpan CLOSEH3\n                    empty :'
    
_lr_action_items = {'OPENH2':([0,],[4,]),'OPENH3':([0,],[5,]),'$end':([0,1,2,3,6,7,26,36,38,51,60,62,],[-32,0,-15,-3,-1,-2,-15,-28,-14,-27,-30,-31,]),'OPENPARA':([2,60,62,],[8,-30,-31,]),'OPENLI':([2,26,60,62,],[9,9,-30,-31,]),'OPENSPAN':([4,5,10,11,12,19,20,21,32,33,34,41,43,45,49,53,54,55,58,],[11,13,11,-22,-23,11,11,-20,11,-21,11,-24,-26,11,11,-25,11,11,11,]),'CLOSESPAN':([4,10,11,12,15,19,20,21,22,23,25,32,33,34,37,41,43,45,47,49,52,53,54,55,56,58,59,],[12,12,21,-23,-4,12,12,-20,33,34,-5,12,-21,12,-6,-24,-26,12,-7,12,-8,-25,12,12,-9,12,-10,]),'CONTENT':([8,9,11,13,15,18,19,24,25,27,28,30,37,41,42,43,47,48,52,53,56,59,],[15,15,15,23,25,15,30,15,37,15,15,42,47,-24,48,-26,52,47,56,-25,59,-10,]),'CLOSELI':([9,15,16,25,27,28,37,39,40,41,43,47,52,53,56,59,],[-13,-4,26,-5,-13,-13,-6,-11,-12,-24,-26,-7,-8,-25,-9,-10,]),'OPENHREF':([9,11,12,14,15,17,21,25,27,28,33,35,37,41,43,44,47,50,52,53,56,59,],[19,-22,-23,19,-4,19,-20,-5,19,19,-21,19,-6,-24,-26,19,-7,19,-8,-25,-9,-10,]),'CLOSEHREF':([11,12,21,29,30,31,33,42,47,48,52,56,59,],[-22,-23,-20,41,-4,43,-21,-5,-7,53,-8,-9,-10,]),'CLOSEH2':([11,12,21,33,57,],[-22,-23,-20,-21,60,]),'CLOSEH3':([11,12,21,33,61,],[-22,-23,-20,-21,62,]),'CLOSEPARA':([24,41,43,46,53,],[36,-24,-26,51,-25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'handleheader':([0,],[2,]),'empty':([0,],[3,]),'dataCell':([2,],[6,]),'dataLI':([2,26,],[7,38,]),'dataSpan':([4,10,19,20,32,34,45,49,54,55,58,],[10,20,31,32,44,45,50,54,57,58,61,]),'dataContent':([8,9,11,18,19,24,27,28,],[14,17,22,28,29,35,17,17,]),'reLI':([9,27,28,],[16,39,40,]),'dataHREF':([9,14,17,27,28,35,44,50,],[18,24,27,18,18,46,49,55,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> handleheader dataCell','start',2,'p_start','extract_info.py',85),
  ('start -> handleheader dataLI','start',2,'p_start','extract_info.py',86),
  ('start -> empty','start',1,'p_start','extract_info.py',87),
  ('dataContent -> CONTENT','dataContent',1,'p_dataContent','extract_info.py',92),
  ('dataContent -> CONTENT CONTENT','dataContent',2,'p_dataContent','extract_info.py',93),
  ('dataContent -> CONTENT CONTENT CONTENT','dataContent',3,'p_dataContent','extract_info.py',94),
  ('dataContent -> CONTENT CONTENT CONTENT CONTENT','dataContent',4,'p_dataContent','extract_info.py',95),
  ('dataContent -> CONTENT CONTENT CONTENT CONTENT CONTENT','dataContent',5,'p_dataContent','extract_info.py',96),
  ('dataContent -> CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT','dataContent',6,'p_dataContent','extract_info.py',97),
  ('dataContent -> CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT CONTENT','dataContent',7,'p_dataContent','extract_info.py',98),
  ('reLI -> dataContent dataHREF reLI','reLI',3,'p_reLI','extract_info.py',121),
  ('reLI -> dataHREF dataContent reLI','reLI',3,'p_reLI','extract_info.py',122),
  ('reLI -> <empty>','reLI',0,'p_reLI','extract_info.py',123),
  ('dataLI -> OPENLI reLI CLOSELI dataLI','dataLI',4,'p_dataLI','extract_info.py',126),
  ('dataLI -> <empty>','dataLI',0,'p_dataLI','extract_info.py',127),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','extract_info.py',130),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','extract_info.py',131),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','extract_info.py',132),
  ('skiptag -> empty','skiptag',1,'p_skiptag','extract_info.py',133),
  ('dataSpan -> OPENSPAN CLOSESPAN','dataSpan',2,'p_dataSpan','extract_info.py',135),
  ('dataSpan -> OPENSPAN dataContent CLOSESPAN','dataSpan',3,'p_dataSpan','extract_info.py',136),
  ('dataSpan -> OPENSPAN','dataSpan',1,'p_dataSpan','extract_info.py',137),
  ('dataSpan -> CLOSESPAN','dataSpan',1,'p_dataSpan','extract_info.py',138),
  ('dataHREF -> OPENHREF dataContent CLOSEHREF','dataHREF',3,'p_dataHREF','extract_info.py',141),
  ('dataHREF -> OPENHREF CONTENT CONTENT CONTENT CLOSEHREF','dataHREF',5,'p_dataHREF','extract_info.py',142),
  ('dataHREF -> OPENHREF dataSpan CLOSEHREF','dataHREF',3,'p_dataHREF','extract_info.py',143),
  ('dataCell -> OPENPARA dataContent dataHREF dataContent dataHREF CLOSEPARA','dataCell',6,'p_dataCell','extract_info.py',146),
  ('dataCell -> OPENPARA dataContent dataHREF CLOSEPARA','dataCell',4,'p_dataCell','extract_info.py',147),
  ('dataCell -> <empty>','dataCell',0,'p_dataCell','extract_info.py',148),
  ('handleheader -> OPENH2 dataSpan dataSpan dataSpan dataSpan dataHREF dataSpan dataSpan CLOSEH2','handleheader',9,'p_handleheader','extract_info.py',151),
  ('handleheader -> OPENH3 OPENSPAN CONTENT CLOSESPAN dataSpan dataSpan dataHREF dataSpan dataSpan CLOSEH3','handleheader',10,'p_handleheader','extract_info.py',152),
  ('empty -> <empty>','empty',0,'p_empty','extract_info.py',161),
]
