
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE BEGINTABLE2 BEGINTABLE3 CLOSEBOLD CLOSEDATA CLOSEDIV CLOSEH3 CLOSEH4 CLOSEHEADER CLOSEHREF CLOSENOBR CLOSEROW CLOSESMALL CLOSESPAN CLOSESTYLE CLOSETABLE CLOSETABLEHEADER CLOSETABLE_TABLE CONTENT GARBAGE IMAGE OPENBOLD OPENBR OPENDATA OPENDIV OPENH3 OPENH4 OPENHEADER OPENHREF OPENLINK OPENNOBR OPENROW OPENSMALL OPENSPAN OPENSTYLE OPENTABLE OPENTABLEHEADER OPENTABLE_TABLEstart : tableskiptag : CONTENT skiptag\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | emptyskiptable : OPENTABLE skiptable\n               | CLOSETABLE skiptable\n               | OPENDATA skiptable\n                | CLOSEDATA skiptable\n                | OPENROW skiptable\n                | CLOSEROW skiptable\n                | OPENDIV skiptable\n                | CLOSEDIV skiptable\n                | CONTENT skiptable\n               | emptyheadcontent : CONTENT CONTENT\n                    | CONTENT\n                    | CONTENT CONTENT CONTENT CONTENT\n                   | empty\n    thead_data : OPENHEADER headcontent CLOSEHEADER thead_data\n                  | empty\n    table_header : OPENROW thead_data CLOSEROW table_header\n                    | empty\n    rowcontent : CONTENT\n                    | CONTENT CONTENT \n                    | empty\n    row_data : OPENDATA rowcontent CLOSEDATA row_data\n                | empty\n    row_handler : OPENROW row_data CLOSEROW row_handler\n                    | empty\n    fulltable : OPENTABLEHEADER table_header CLOSETABLEHEADER fulltable\n                | OPENTABLE row_handler CLOSETABLE fulltable\n\n                | empty\n\n    table : BEGINTABLE OPENDIV OPENTABLE_TABLE fulltableempty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,5,6,9,16,20,24,29,],[0,-1,-35,-34,-33,-35,-35,-31,-32,]),'OPENDIV':([3,],[4,]),'OPENTABLE_TABLE':([4,],[5,]),'OPENTABLEHEADER':([5,16,20,],[7,7,7,]),'OPENTABLE':([5,16,20,],[8,8,8,]),'OPENROW':([7,8,25,30,],[11,14,11,14,]),'CLOSETABLEHEADER':([7,10,12,25,34,],[-35,16,-23,-35,-22,]),'CLOSETABLE':([8,13,15,30,37,],[-35,20,-30,-35,-29,]),'OPENHEADER':([11,35,],[18,18,]),'CLOSEROW':([11,14,17,19,21,23,35,38,40,42,],[-35,-35,25,-21,30,-28,-35,-35,-20,-27,]),'OPENDATA':([14,38,],[22,22,]),'CONTENT':([18,22,27,32,36,41,],[27,32,36,39,41,43,]),'CLOSEHEADER':([18,26,27,28,36,43,],[-35,35,-17,-19,-16,-18,]),'CLOSEDATA':([22,31,32,33,39,],[-35,38,-24,-26,-25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'fulltable':([5,16,20,],[6,24,29,]),'empty':([5,7,8,11,14,16,18,20,22,25,30,35,38,],[9,12,15,19,23,9,28,9,33,12,15,19,23,]),'table_header':([7,25,],[10,34,]),'row_handler':([8,30,],[13,37,]),'thead_data':([11,35,],[17,40,]),'row_data':([14,38,],[21,42,]),'headcontent':([18,],[26,]),'rowcontent':([22,],[31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','extract.py',191),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','extract.py',196),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','extract.py',197),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','extract.py',198),
  ('skiptag -> empty','skiptag',1,'p_skiptag','extract.py',199),
  ('skiptable -> OPENTABLE skiptable','skiptable',2,'p_skiptable','extract.py',203),
  ('skiptable -> CLOSETABLE skiptable','skiptable',2,'p_skiptable','extract.py',204),
  ('skiptable -> OPENDATA skiptable','skiptable',2,'p_skiptable','extract.py',205),
  ('skiptable -> CLOSEDATA skiptable','skiptable',2,'p_skiptable','extract.py',206),
  ('skiptable -> OPENROW skiptable','skiptable',2,'p_skiptable','extract.py',207),
  ('skiptable -> CLOSEROW skiptable','skiptable',2,'p_skiptable','extract.py',208),
  ('skiptable -> OPENDIV skiptable','skiptable',2,'p_skiptable','extract.py',209),
  ('skiptable -> CLOSEDIV skiptable','skiptable',2,'p_skiptable','extract.py',210),
  ('skiptable -> CONTENT skiptable','skiptable',2,'p_skiptable','extract.py',211),
  ('skiptable -> empty','skiptable',1,'p_skiptable','extract.py',212),
  ('headcontent -> CONTENT CONTENT','headcontent',2,'p_headcontent','extract.py',217),
  ('headcontent -> CONTENT','headcontent',1,'p_headcontent','extract.py',218),
  ('headcontent -> CONTENT CONTENT CONTENT CONTENT','headcontent',4,'p_headcontent','extract.py',219),
  ('headcontent -> empty','headcontent',1,'p_headcontent','extract.py',220),
  ('thead_data -> OPENHEADER headcontent CLOSEHEADER thead_data','thead_data',4,'p_thead_data','extract.py',236),
  ('thead_data -> empty','thead_data',1,'p_thead_data','extract.py',237),
  ('table_header -> OPENROW thead_data CLOSEROW table_header','table_header',4,'p_table_header','extract.py',242),
  ('table_header -> empty','table_header',1,'p_table_header','extract.py',243),
  ('rowcontent -> CONTENT','rowcontent',1,'p_rowcontent','extract.py',250),
  ('rowcontent -> CONTENT CONTENT','rowcontent',2,'p_rowcontent','extract.py',251),
  ('rowcontent -> empty','rowcontent',1,'p_rowcontent','extract.py',252),
  ('row_data -> OPENDATA rowcontent CLOSEDATA row_data','row_data',4,'p_row_data','extract.py',268),
  ('row_data -> empty','row_data',1,'p_row_data','extract.py',269),
  ('row_handler -> OPENROW row_data CLOSEROW row_handler','row_handler',4,'p_row_handler','extract.py',274),
  ('row_handler -> empty','row_handler',1,'p_row_handler','extract.py',275),
  ('fulltable -> OPENTABLEHEADER table_header CLOSETABLEHEADER fulltable','fulltable',4,'p_fulltable','extract.py',282),
  ('fulltable -> OPENTABLE row_handler CLOSETABLE fulltable','fulltable',4,'p_fulltable','extract.py',283),
  ('fulltable -> empty','fulltable',1,'p_fulltable','extract.py',285),
  ('table -> BEGINTABLE OPENDIV OPENTABLE_TABLE fulltable','table',4,'p_table','extract.py',290),
  ('empty -> <empty>','empty',0,'p_empty','extract.py',293),
  ('content -> CONTENT','content',1,'p_content','extract.py',298),
  ('content -> empty','content',1,'p_content','extract.py',299),
]
